### ISSUE TITLE
ability to restart a ticket

### ISSUE THREAD

**Issue by DaNiSoFt** [fernandokosh/redmine_time_tracker#8] opened 2010-03-30 09:11 UTC
Would be nice to have the ability to enter a comment 
OR to restart a ticket instead of entering a comment

Extra:
A list of running tickets where only one ticket can be active

**Comment by delaitre** [comment] 2010-03-30 10:13
What do you mean by "restart a ticket" ?
If you just want to restart the current time tracker, you can click on "stop #xxx". This will redirect you to the "log spent time" page. Here, you just have to click to another page and the time will not be logged.
I know this is far from ideal, but I did not find a good way to "restart" the time tracker. I mean, I though to add a "cancel" link next to the "close" link, but I think it will take too much space in the menu. Maybe a hierarchical menu will be better (I think this is the better solution) but I didn't have the time to try that yet.

For the "extra", I didn't undestand your request... can you describe it more precisely ?

**Comment by DaNiSoFt** [comment] 2010-03-30 10:30
For example an restart-link where the ticket just starts on that time where it was stopped.

For extra:
If I stop a ticket and maybe start an other ticket and did not enter a time for the stopped one... 

the stopped ticket appears in a list where it is possible to save, restart or cancel
time tracking.

**Comment by delaitre** [comment] 2010-03-30 11:14
If I understand correctly, this is more a "continue" link than a "restart" one. However, I didn't think this is really useful.
The only use case which comes in my mind will be if you forget to start the time tracker for your current task. However, there is a lot of chance that you don't want to track the time from the last stop, and it this case, the "continue" link will be helpless.

For your extra:
When you stop the time tracker, the spent time field is pre-filled with the time tracker value (indeed, this is THE feature of this plugin, this is why I wrote it!). Thus, you don't have to "enter" a time for the stopped issue. You just have to select an activity, and validate the new "spent time" entry.
To start the time tracker on another issue, you have to stop it for the current one. Thus, if you fall into the situation where you start the time tracker on another issue, and you don't save the spent time of the last tracked one, I can't do anything for you (and, really, you didn't use the plugin as it is design for).

The plugin was designed to have a really simple and smooth workflow. Keeping an history of the time trackers and so, or adding feature which are not well defined or really useful is conflicting with this plugin nature.

**Comment by DaNiSoFt** [comment] 2010-03-30 12:37
Yes it is to continue the time what I mean.

And to be able to start more than one ticket 
but only one actually running per user
(the others are stopped in "background")

Therefore there could be a list like:

Ticket 1 (running)  - 0.25h    -   [stop]        -       [save]    -     [cancel]
Ticket 2 (stopped) -  1 h  -    [continue]     -      [save]    -     [cancel]
Ticket 3 (stopped) -  2 h  -    [continue]     -      [save]    -     [cancel]

the running ticket always is in the menu on top

If one ticket gets  continued - the running one is stopped

For me it often happens that work on more than one project
or task on one day.....

but I also see that it is some work to do.
And unfortunately my time also is quite rare.

**Comment by delaitre** [comment] 2010-03-31 08:55
Ok, it's clearer in my mind now :)
Your use case is quite common indeed, thus I'm starting to love your idea.
Moreover, I'm really not happy with the current flow to "cancel" a time tracker, yours is better.

A remark though: When using the "continue" option, the time spent is, in reality, ceased. When you'll "save" the time tracker, the spent time logged is a continue one. I don't think Redmine check if the log time entries doesn't overlap, thus we could log it without problem, but this will not reflect the realty of the time spent. However, this should be ok for most user.

As it requires some work to do, I'd like to hear what other users think about this feature.

At time being, I personally open one tab by ticket in my browser, and I switch from one to the other when needed... not ideal but this is better than without the plugin :)

**Comment by DaNiSoFt** [comment] 2010-03-31 11:25
First I want to say that I like Ur plugin very and it makes it much easier to track time !

What I mean is:
If I spent already 0.25 h on a ticket and press continue than the tracking should
start with 0.25 h for that ticket again.

If the "save" button is pressed the user should be able to write ONE
comment to the sum of times.

**Comment by delaitre** [comment] 2010-03-31 11:32
Yes, this is what I understood.
Forget what I say about time overlapping, this will probably never happen since the time log form doesn't require a "start time", but only the day of the work. Thus, time overlapping could occurs only if you run a time tracker longer than a day which should not happen.

**Comment by delaitre** [comment] 2010-05-04 14:48
I think I will finally implement this feature some day as it will simplify my workflow too. Don't now when though.

**Comment by ghost** [comment] 2010-05-06 22:21
Please integrate this feature. It will be very useful, just some kind of pause on current issue and then continue the work.
Big thanks for your module!

**Comment by kalbasit** [comment] 2010-05-28 09:39
+1 on this request, thanks for your effort!

**Comment by delaitre** [comment] 2011-02-09 13:13
Little update just to let you know that you can pause/resume the current time tracker now.
However, multiple per-user time trackers is not implemented yet.

**Comment by delaitre** [comment] 2011-12-05 14:15
I'm closing this issue as the stop/resume feature is implemented. The issue #61 will be used to discuss the "multi-tracker" feature.

**Closed as completed by delaitre** 2011-12-05 14:15 UTC
Labels: Feature
