### ISSUE TITLE
404 Error 

### ISSUE THREAD

**Issue by tiagonpsilva** [fernandokosh/redmine_time_tracker#34] opened 2010-11-20 07:45 UTC
Hi,

When the task is stopped, the error message is displayed:
404 - The page you were trying to access doesn't exist or has been removed.

The action executed is:
http://.../timelog/edit?issue_id=2&time_entry[hours]=0.02

Thanks

**Comment by delaitre** [comment] 2010-11-20 12:40
Which version of redmine and of the plugin do you run ?

**Comment by tiagonpsilva** [comment] 2010-11-20 23:47
1.0.3.

**Comment by delaitre** [comment] 2010-11-21 12:10
And the plugin version ?

**Comment by delaitre** [comment] 2010-11-21 12:11
And why did you close the bug? Is this fixed?

**Comment by tiagonpsilva** [comment] 2010-11-21 18:55
The plugin version is 0.3. This isn't fixed. 

Thanks

**Comment by delaitre** [comment] 2010-11-21 20:18
Well, this is strange and I've no idea where it can come from... I have not tested redmine 1.0.3 yet but I'll when time permits...

**Comment by timir0n** [comment] 2010-11-30 06:14
I have the same error 404
when executed http://my_collab/timelog/edit?issue_id=727&time_entry[hours]=0.22
redmine version 1.0.4

**Comment by MischaTheEvil** [comment] 2010-11-30 21:12
Jérémie,

This issue is still present in the most recent version of the plugin. It is caused by the changes in the Redmine trunk regarding the changed controller actions.

It has been fixed in several forks, see:
- https://github.com/lilly-jp/redmine_time_tracker/commit/a1878eff40820cf77b082ab9515c20b3e80420b3
- https://github.com/managedit/redmine_time_tracker/commit/1dc3451095b9dadb014b6d4226969ed85cbf1c85

**Comment by delaitre** [comment] 2010-12-01 09:42
This seems like #30.

Looking at timelog_controller.rb in redmine 1.0.4 (http://www.redmine.org/projects/redmine/repository/entry/tags/1.0.4/app/controllers/timelog_controller.rb) it seems the action is still "edit", not "new". I have no time yet to test it (I've just look in the file).

Are you sure you are running redmine 1.0.4 and not trunk?

**Comment by MischaTheEvil** [comment] 2010-12-01 20:00
I am on trunk and I was aware of that while posting. Though, hadn't noticed that the other users were all talking about the 1.0-STABLE branch...
I haven't said anything... ;-)

(Btw: thanks for maintaining this plugin...)

**Comment by delaitre** [comment] 2010-12-29 10:28
This can't be reproduced... However redmine 1.1.0 should be available in 11 days and the logging stuff has been changed for this release.

The master branch of the plugin contains a fix (thanks to MischaTheEvil) which is compatible with both redmine 1.0.x and redmine trunk. However, this should not fix this bug is you have it...

**Closed as completed by delaitre** 2010-12-29 10:28 UTC
Labels: Bug
